name: da5ide
favicon: null
layout_spectrum: 0.73948
typography_spectrum: 0.3137
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Davide A.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#000000'
    - '#bcbebd'
    - '#858688'
    - '#494a4c'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
