name: tanukiexpress
favicon: null
layout_spectrum: 0.5548845843877643
typography_spectrum: 0.38690569205209613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.012325933668762445
  lightness: 0.1187434031162411
  saturation: 0.5318315806798637
  rhythmicContrast: 0.15965942945331335
purpose: []
